spring:
  application:
    name: PetCare

  #Για χρήση postgrase:
#  datasource:
#    url: jdbc:postgresql://dpg-d5jr16ur433s73b87140-a.frankfurt-postgres.render.com:5432/petcaredb_n3dc
#    username: petcareuser
#    password: FLKGrdjOVunzzbjhjBD75LSxeQduxw63
#    driver-class-name: org.postgresql.Driver
#
#    jpa:
#      hibernate:
#        # κάθε φορά που τρέχουμε την εφαρμογή,
#        # φτιάχνει ξανά τους πίνακες και στο τέλος τους σβήνει.
#        ddl-auto: create-drop
#      open-in-view: false
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#          format_sql: true
  datasource:
    # H2 database - κρατάει δεδομένα στον φάκελο LOCAL_DATA
    url: jdbc:h2:file:./LOCAL_DATA/h2/app;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password: changeme
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # κάθε φορά που τρέχουμε την εφαρμογή,
      # φτιάχνει ξανά τους πίνακες και στο τέλος τους σβήνει.
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  h2:
    console:
      enabled: true
      # βλέπουμε τη βάση στον browser 
      path: /h2-console

# Εξωτερικές υπηρεσίες (black box)
# Η PetCare τις καλεί μέσω HTTP

external:
  sms-service:
    # URL της εξωτερικής υπηρεσίας SMS (PetCare Notification Service)
    # Η PetCare ΔΕΝ ξέρει την υλοποίηση, μόνο αυτό το endpoint.
    url: http://localhost:8081/api/v1/sms

  phone-service:
    # Base URL για έλεγχο/κανονικοποίηση τηλεφώνου (E.164)
    # GET {url}/{phone}/validations
    url: http://localhost:8081/api/v1/phone-numbers

  vaccines-service:
    # Base URL για mock λίστα τυπικών εμβολίων ανά είδος ζώου
    # GET {url}/{species}
    url: http://localhost:8081/api/v1/vaccines





security:
  jwt:
    issuer: petcare
    secret: "password_changeme_secret_key_FF1234567890"
    expiration-minutes: 120
